changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels: ["breaking-change"]
    - title: Added
      labels: ["enhancement"]
    - title: Deprecated
      labels: ["deprecation"]
    - title: Fixed
      labels: ["bug"]
    - title: Documentation
      labels: ["documentation"]
    - title: Other Changes
      labels: ["*"]
      exclude:
        labels:
          - "tests-only"
          - "dependencies"
          - "workflows"
        authors:
          - "dependabot"
    - title: Miscellaneous
      labels: ["*"]
