# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    BIDI_DESC_REQ3 = "A string with RandALCat characters must start and end with RandALCat characters."

  end
end
