# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Unassigned code points in Unicode 3.2 \StringPrep\[\"A.1\"]
    IN_A_1 = /\p{^AGE=3.2}/.freeze

  end
end
