# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Non-character code points \StringPrep\[\"C.4\"]
    IN_C_4 = /\p{noncharacter code point}/.freeze

  end
end
