# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Inappropriate for canonical representation \StringPrep\[\"C.7\"]
    IN_C_7 = /[\p{in ideographic description characters}&&\p{AGE=3.2}]/.freeze

  end
end
