# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # ASCII control characters \StringPrep\[\"C.2.1\"]
    IN_C_2_1 = /[\x00-\x1f\x7f]/.freeze

  end
end
