# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Surrogate codes \StringPrep\[\"C.5\"]
    IN_C_5 = /\p{surrogate}/.freeze

  end
end
