# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Private use \StringPrep\[\"C.3\"]
    IN_C_3 = /\p{private use}/.freeze

  end
end
