# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Tagging characters \StringPrep\[\"C.9\"]
    IN_C_9 = /[\p{in Tags}&&\p{AGE=3.2}]/.freeze

  end
end
