# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # ASCII space characters \StringPrep\[\"C.1.1\"]
    IN_C_1_1 = / /.freeze

  end
end
