# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Replacements for IN_B.1
    MAP_B_1 = {"­" => "", "͏" => "", "᠆" => "", "᠋" => "", "᠌" => "", "᠍" => "", "​" => "", "‌" => "", "‍" => "", "⁠" => "", "︀" => "", "︁" => "", "︂" => "", "︃" => "", "︄" => "", "︅" => "", "︆" => "", "︇" => "", "︈" => "", "︉" => "", "︊" => "", "︋" => "", "︌" => "", "︍" => "", "︎" => "", "️" => "", "﻿" => ""}.freeze

  end
end
