# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Regexps and substitutions matching the RFC-3454 Appendix B tables
    MAPPINGS = {
      "B.1" => [IN_B_1, MAP_B_1].freeze,
      "B.2" => [IN_B_2, MAP_B_2].freeze,
      "B.3" => [IN_B_3, MAP_B_3].freeze,
    }.freeze

  end
end
