# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Combines C.1.2, C.2.2, C.3, C.4, C.5, C.6, C.7, C.8, C.9,
    # and A.1.  Used by the "nameprep" profile.
    NAMEPREP_PROHIBIT_STORED =
      Regexp.union(IN_A_1, NAMEPREP_PROHIBIT).freeze

  end
end
