# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Regexps matching each codepoint table in the RFC-3454 appendices
    REGEXPS = {
      "A.1"   => IN_A_1,
      "B.1"   => IN_B_1,
      "B.2"   => IN_B_2,
      "B.3"   => IN_B_3,
      "C.1.1" => IN_C_1_1,
      "C.1.2" => IN_C_1_2,
      "C.2.1" => IN_C_2_1,
      "C.2.2" => IN_C_2_2,
      "C.3"   => IN_C_3,
      "C.4"   => IN_C_4,
      "C.5"   => IN_C_5,
      "C.6"   => IN_C_6,
      "C.7"   => IN_C_7,
      "C.8"   => IN_C_8,
      "C.9"   => IN_C_9,
      "D.1"   => IN_D_1,
      "D.2"   => IN_D_2,
    }.freeze

  end
end
