# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Names of each codepoint table in the RFC-3454 appendices
    TITLES = {
      "A.1"   => "Unassigned code points in Unicode 3.2",
      "B.1"   => "Commonly mapped to nothing",
      "B.2"   => "Mapping for case-folding used with NFKC",
      "B.3"   => "Mapping for case-folding used with no normalization",
      "C.1"   => "Space characters",
      "C.1.1" => "ASCII space characters",
      "C.1.2" => "Non-ASCII space characters",
      "C.2"   => "Control characters",
      "C.2.1" => "ASCII control characters",
      "C.2.2" => "Non-ASCII control characters",
      "C.3"   => "Private use",
      "C.4"   => "Non-character code points",
      "C.5"   => "Surrogate codes",
      "C.6"   => "Inappropriate for plain text",
      "C.7"   => "Inappropriate for canonical representation",
      "C.8"   => "Change display properties or are deprecated",
      "C.9"   => "Tagging characters",
      "D.1"   => "Characters with bidirectional property \"R\" or \"AL\"",
      "D.2"   => "Characters with bidirectional property \"L\"",
    }.freeze

  end
end
