# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    # Combines C.2.1, C.2.2, C.3, C.4, C.5, C.6, C.8, C.9,
    # and A.1.  Used by the "trace" profile.
    TRACE_PROHIBIT_STORED =
      Regexp.union(IN_A_1, TRACE_PROHIBIT).freeze

  end
end
