# frozen_string_literal: true

#--
# This file is generated by `rake stringprep:tables`.  Don't edit directly.
#++

module Net::IMAP::StringPrep
  module Tables

    autoload :IN_A_1,                   "#{__dir__}/tables/in_a_1.rb"
    autoload :IN_B_1,                   "#{__dir__}/tables/in_b_1.rb"
    autoload :IN_B_2,                   "#{__dir__}/tables/in_b_2.rb"
    autoload :IN_B_3,                   "#{__dir__}/tables/in_b_3.rb"
    autoload :IN_C_1_1,                 "#{__dir__}/tables/in_c_1_1.rb"
    autoload :IN_C_1_2,                 "#{__dir__}/tables/in_c_1_2.rb"
    autoload :IN_C_2_1,                 "#{__dir__}/tables/in_c_2_1.rb"
    autoload :IN_C_2_2,                 "#{__dir__}/tables/in_c_2_2.rb"
    autoload :IN_C_3,                   "#{__dir__}/tables/in_c_3.rb"
    autoload :IN_C_4,                   "#{__dir__}/tables/in_c_4.rb"
    autoload :IN_C_5,                   "#{__dir__}/tables/in_c_5.rb"
    autoload :IN_C_6,                   "#{__dir__}/tables/in_c_6.rb"
    autoload :IN_C_7,                   "#{__dir__}/tables/in_c_7.rb"
    autoload :IN_C_8,                   "#{__dir__}/tables/in_c_8.rb"
    autoload :IN_C_9,                   "#{__dir__}/tables/in_c_9.rb"
    autoload :IN_D_1,                   "#{__dir__}/tables/in_d_1.rb"
    autoload :IN_D_1_NEGATED,           "#{__dir__}/tables/in_d_1_negated.rb"
    autoload :IN_D_2,                   "#{__dir__}/tables/in_d_2.rb"
    autoload :MAP_B_1,                  "#{__dir__}/tables/map_b_1.rb"
    autoload :MAP_B_2,                  "#{__dir__}/tables/map_b_2.rb"
    autoload :MAP_B_3,                  "#{__dir__}/tables/map_b_3.rb"
    autoload :BIDI_DESC_REQ2,           "#{__dir__}/tables/bidi_desc_req2.rb"
    autoload :BIDI_FAILS_REQ2,          "#{__dir__}/tables/bidi_fails_req2.rb"
    autoload :BIDI_DESC_REQ3,           "#{__dir__}/tables/bidi_desc_req3.rb"
    autoload :BIDI_FAILS_REQ3,          "#{__dir__}/tables/bidi_fails_req3.rb"
    autoload :BIDI_FAILURE,             "#{__dir__}/tables/bidi_failure.rb"
    autoload :SASLPREP_PROHIBIT,        "#{__dir__}/tables/saslprep_prohibit.rb"
    autoload :SASLPREP_PROHIBIT_STORED, "#{__dir__}/tables/saslprep_prohibit_stored.rb"
    autoload :TRACE_PROHIBIT,           "#{__dir__}/tables/trace_prohibit.rb"
    autoload :TRACE_PROHIBIT_STORED,    "#{__dir__}/tables/trace_prohibit_stored.rb"
    autoload :NAMEPREP_PROHIBIT,        "#{__dir__}/tables/nameprep_prohibit.rb"
    autoload :NAMEPREP_PROHIBIT_STORED, "#{__dir__}/tables/nameprep_prohibit_stored.rb"
    autoload :TITLES,                   "#{__dir__}/tables/titles.rb"
    autoload :REGEXPS,                  "#{__dir__}/tables/regexps.rb"
    autoload :MAPPINGS,                 "#{__dir__}/tables/mappings.rb"

  end
end
